services:
<<<<<<< HEAD
  database:
    image: postgres
    container_name: databasewpp
=======
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_ignite
>>>>>>> 38bab011f27f69eb298bb76a2dc71fd30f19f3fa
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=academy
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=academywestpoint
    volumes:
      - pgdata:/data/postgres
<<<<<<< HEAD
    network_mode: host

  redis:
    image: redis
    container_name: academy_rediss
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  redis-commander:
    container_name: academy_redis-commanderr
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  app:
    build: .
    container_name: academywestpointtt
    restart: always
    environment:
      REDIS_URL: redis:6379
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: 1000
=======


  app:
    build: .
    container_name: academywestpoint
    restart: always
>>>>>>> 38bab011f27f69eb298bb76a2dc71fd30f19f3fa
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
<<<<<<< HEAD
    network_mode: host
    depends_on:
      - redis
=======
    links: 
      - database
    depends_on:
      - database


>>>>>>> 38bab011f27f69eb298bb76a2dc71fd30f19f3fa

volumes:
  pgdata:
    driver: local