version: "3.7"

services:
  database:
    image: postgres
    container_name: databasewp
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=academy
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=academywestpoint
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: academywestpointt
    restart: always
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local