import { AppBar, Link, Toolbar, Typography } from '@mui/material';
import Head from 'next/head';
import NextLink from 'next/link';

export default function Header() {
  return (
    <>
      <Head>
        <title>Westpoint</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppBar position='static'>
        <Toolbar variant='dense'>
          <NextLink href='/dashboard'>
            <Link href='#' color='white' underline='none' width='100%'>
              <Typography textAlign='center' variant='h5'>
                WestPoint Exchange
              </Typography>
            </Link>
          </NextLink>
        </Toolbar>
      </AppBar>
    </>
  );
}
