import { AppBar, Button, Link, Toolbar, Typography } from '@mui/material';
import Head from 'next/head';
import NextLink from 'next/link';
import { useTranslation } from 'next-i18next';
import { useRouter } from 'next/router';

export default function Header() {
  const { t } = useTranslation('common');
  const router = useRouter();

  return (
    <>
      <Head>
        <title>{t('name')}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppBar position='static'>
        <Toolbar variant='dense'>
          <NextLink href='/dashboard'>
            <Link href='#' color='white' underline='none' width='100%'>
              <Typography textAlign='center' variant='h5'>
                {t('title')}
              </Typography>
            </Link>
          </NextLink>
          <NextLink
            locale={router.locale === 'en' ? 'pt' : 'en'}
            href={router.pathname}
          >
            <Button
              size='small'
              variant='contained'
              sx={{
                position: 'absolute',
                alignSelf: 'flex-end',
              }}
            >
              {t('langConfig')}
            </Button>
          </NextLink>
        </Toolbar>
      </AppBar>
    </>
  );
}
